package main
const (
    WALL = '#'
    PLAYER = '☺'
    PLAYER_BUMP = '☻'
    FOG = '?'
    OPEN = ' '
    //FOG ='░'

    V_WALL = '│'
    H_WALL = '─'
    TL_CORNER = '┌'
    TR_CORNER = '┐'
    BR_CORNER = '┘'
    BL_CORNER = '└'
    T_INTERSECT = '┬'
    R_INTERSECT = '┤'
    B_INTERSECT = '┴'
    L_INTERSECT = '├'
    C_INTERSECT = '┼'
    T_STUB = '╵'
    R_STUB = '╶'
    B_STUB = '╷'
    L_STUB = '╴'
)
